package com.example.ui

object LocalizedStrings {
    private val es = mapOf(
        "app_title" to "You",
        "login_subtitle" to "Modo de extrema productividad.",
        "login_phone" to "Continuar con Teléfono",
        "login_google" to "Continuar con Google",
        "login_microsoft" to "Continuar con Microsoft",
        "goals_title" to "Tus Metas",
        "no_goals" to "No tienes metas aún. Agrega una para comenzar.",
        "add_goal" to "Nueva Meta de Enfoque",
        "goal_input_label" to "¿Qué vas a aprender?",
        "duration_input_label" to "Duración (minutos)",
        "add_button" to "Agregar",
        "cancel_button" to "Cancelar",
        "pending" to "Pendiente",
        "completed" to "Completado",
        "focus_mode" to "MODO DE ENFOQUE",
        "focus_desc" to "Todas las demás apps están bloqueadas.",
        "complete_unlock" to "RECOMPENSA Y DESBLOQUEAR",
        "achievements_title" to "Logros",
        "ranking_title" to "Ranking Global",
        "profile_title" to "Configuración de Perfil",
        "edit_profile" to "Editar Perfil",
        "app_settings" to "Configuración",
        "logout" to "Cerrar Sesión",
        "achievement_1_title" to "Primer Enfoque",
        "achievement_1_desc" to "Completa tu primera sesión",
        "achievement_2_title" to "Estudiante Dedicado",
        "achievement_2_desc" to "Completa 5 sesiones de enfoque",
        "achievement_3_title" to "Gurú del Enfoque",
        "achievement_3_desc" to "Acumula 10 horas de enfoque sin distracciones",
        "achievement_4_title" to "Racha de 3 Días",
        "achievement_4_desc" to "Enfócate por 3 días seguidos",
        "switch_language" to "Cambiar Idioma",
        "profile_level" to "Nivel: Principiante del Enfoque",
        "tab_home" to "Inicio",
        "tab_achievements" to "Logros",
        "tab_ranking" to "Ranking",
        "tab_profile" to "Perfil",
        "tab_duels" to "Duelos",
        "you" to "Tú",
        "hrs" to "hrs",
        "mins" to "mins",
        "interests_label" to "Tus Intereses Focus",
        "long_term_goals_label" to "Objetivos a Largo Plazo",
        "gender_label" to "Género",
        "male" to "Hombre",
        "female" to "Mujer",
        "neutral" to "Neutro",
        "add_interest_hint" to "Escribe un interés...",
        "add_goal_hint" to "Escribe un objetivo...",
        "settings_title" to "Configuración de Bloqueo",
        "vpn_service" to "Protección VPN Anti-Nopor y Redes",
        "vpn_desc" to "Filtra dominios para adultos y redes sociales a nivel de red.",
        "acc_service" to "Servicio de Accesibilidad (Bloqueo Extremo)",
        "acc_desc" to "Evita salir de You y controla la Whitelist.",
        "wa_timer" to "Temporizador de WhatsApp",
        "wa_timer_desc" to "Permite abrir WhatsApp un máximo de 3-5 minutos.",
        "motivational_title" to "Estímulo de Enfoque",
        "interests_coding" to "Programación",
        "interests_design" to "Diseño Gráfico",
        "interests_reading" to "Lectura",
        "interests_sport" to "Deporte y Salud"
    )

    private val en = mapOf(
        "app_title" to "You",
        "login_subtitle" to "Extreme productivity mode.",
        "login_phone" to "Continue with Phone",
        "login_google" to "Continue with Google",
        "login_microsoft" to "Continue with Microsoft",
        "goals_title" to "Your Goals",
        "no_goals" to "No goals yet. Add one to start focusing.",
        "add_goal" to "New Focus Goal",
        "goal_input_label" to "What will you learn?",
        "duration_input_label" to "Duration (minutes)",
        "add_button" to "Add",
        "cancel_button" to "Cancel",
        "pending" to "Pending",
        "completed" to "Completed",
        "focus_mode" to "FOCUS MODE",
        "focus_desc" to "All other apps are blocked.",
        "complete_unlock" to "RECLAIM & UNLOCK",
        "achievements_title" to "Achievements",
        "ranking_title" to "Global Ranking",
        "profile_title" to "Profile Settings",
        "edit_profile" to "Edit Profile",
        "app_settings" to "Settings",
        "logout" to "Log Out",
        "achievement_1_title" to "First Focus",
        "achievement_1_desc" to "Complete your first focus session",
        "achievement_2_title" to "Dedicated Student",
        "achievement_2_desc" to "Complete 5 focus sessions",
        "achievement_3_title" to "Focus Guru",
        "achievement_3_desc" to "Accumulate 10 hours of pure focus",
        "achievement_4_title" to "3-Day Streak",
        "achievement_4_desc" to "Focus for 3 days in a row",
        "switch_language" to "Switch Language",
        "profile_level" to "Level: Focus Novice",
        "tab_home" to "Home",
        "tab_achievements" to "Achievements",
        "tab_ranking" to "Ranking",
        "tab_profile" to "Profile",
        "tab_duels" to "Duels",
        "you" to "You",
        "hrs" to "hrs",
        "mins" to "mins",
        "interests_label" to "Focus Interests",
        "long_term_goals_label" to "Long-Term Goals",
        "gender_label" to "Gender",
        "male" to "Male",
        "female" to "Female",
        "neutral" to "Neutral",
        "add_interest_hint" to "Type an interest...",
        "add_goal_hint" to "Type a long-term goal...",
        "settings_title" to "Block Settings",
        "vpn_service" to "Anti-Porn & Network Shield VPN",
        "vpn_desc" to "Filters background domain distraction and sites at network layer.",
        "acc_service" to "Accessibility Locker Service",
        "acc_desc" to "Guarantees device overlay lock to sustain whitelists.",
        "wa_timer" to "WhatsApp Grace Timer",
        "wa_timer_desc" to "Allows brief WhatsApp check-ins for 3 to 5 minutes.",
        "motivational_title" to "Focus Spark",
        "interests_coding" to "Software Engineering",
        "interests_design" to "UI/UX Design",
        "interests_reading" to "Book Reading",
        "interests_sport" to "Sports & Mindset"
    )

    fun get(key: String, lang: String): String {
        val dictionary = if (lang.lowercase() == "en") en else es
        return dictionary[key] ?: key
    }
}
